language: cpp

before_install:
 - sudo add-apt-repository -y ppa:brad-froehle/backports #newer mpi4py
 - sudo add-apt-repository -y ppa:boost-latest/ppa  # boost 1.55
 - sudo apt-get update
 - sudo apt-get install cmake libfftw3-dev libopenmpi-dev openmpi-bin
 - if [[ $EXTERNAL = ON ]]; then sudo apt-get install libboost1.55-all-dev python-mpi4py; fi
 - if [[ $BUILD_UG = ON ]]; then sudo apt-get install python-sphinx python-matplotlib && git clone https://github.com/espressopp/espressopp.github.io.git doc/ug/_build/html; fi
 - if [[ $BUILD_UG = ON ]]; then wget --no-check-certificate -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:3}/cmake-${CMAKE_VERSION}.tar.gz | tar -xz && export cmake=$PWD/cmake-${CMAKE_VERSION}/bin/cmake; fi

env: #maybe add mpich later
  - EXTERNAL=ON BUILD_UG=ON CMAKE_VERSION=3.1.3-Linux-x86_64
  - EXTERNAL=OFF

script:
  - mkdir build && cd build && 
    ${cmake:=cmake} -DEXTERNAL_BOOST=$EXTERNAL -DEXTERNAL_MPI4PY=$EXTERNAL .. && 
    make -j4 all ${BUILD_UG:+ug} &&
    make test ARGS="-V" &&
    sudo make install

after_success:
  - if [[ ${BUILD_UG} = ON && ${TRAVIS_JOB_NUMBER} = *.1 ]]; then
      cd ../doc/ug/_build/html/;
      if [[ ${TRAVIS_BRANCH} = master && ${TRAVIS_REPO_SLUG} = espressopp/espressopp && ${TRAVIS_PULL_REQUEST} == false ]] && ! git diff --quiet; then
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "espp-devel@listserv.mpip-mainz.mpg.de";
        git add --all && git commit -m "Documentation Update";
        openssl aes-256-cbc -K $encrypted_194b3d1e9306_key -iv $encrypted_194b3d1e9306_iv -in ../../deploy.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        git push git@github.com:espressopp/espressopp.github.io.git master;
      else
        git diff --no-color;
      fi;
    fi

compiler:
  - clang
  - gcc
